name: boot_serialization
description: Serialization annotations for Boot (@Serdeable).
repository: https://github.com/zonnedev/dart-boot/tree/main/packages/boot_serialization
version: 0.1.1+2
environment:
  sdk: ^3.5.0
resolution: workspace
dependencies:
  boot_core: ^0.1.0

topics:
  - boot
  - serialization
  - json
  - codegen
