name: boot_http_common
description: Shared HTTP primitives for Boot (Request, Response, Filter).
repository: https://github.com/zonnedev/dart-boot/tree/master/packages/boot_http_common
version: 0.1.2
environment:
  sdk: ^3.5.0
resolution: workspace
dependencies:
  boot_core: ^0.1.2+2
  shelf: ^1.4.0

dev_dependencies:
  test: ^1.25.0

topics:
  - boot
  - http
  - server
