name: boot_workspace
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - packages/boot_core
  - packages/boot_aop
  - packages/boot_events
  - packages/boot_scheduling
  - packages/boot_serialization
  - packages/boot_http_common
  - packages/boot_http
  - packages/boot_http_client
  - packages/boot
  - packages/boot_generator
  - packages/boot_test
  - packages/boot_cli

dev_dependencies:
  melos: ^7.7.0

melos:
  repository: https://github.com/zonnedev/dart-boot

  command:
    version:
      branch: master
      linkToCommits: true
      workspaceChangelog: true
      includeCommitId: true
      message: |
        chore(release): publish packages

        {new_package_versions}
      hooks:
        preCommit: dart run scripts/update_cli_version.dart

  scripts:
    analyze:
      exec: dart analyze
    test:
      exec: dart test
      packageFilters:
        dirExists: test
    coverage:
      run: melos exec --concurrency=1 -- "dart pub global run coverage:test_with_coverage" && dart run scripts/coverage_report.dart
      packageFilters:
        dirExists: test
    build:
      exec: dart run build_runner build --delete-conflicting-outputs
      packageFilters:
        fileExists: build.yaml
