name: todo_app
description: Guide 021 - Declarative HTTP Client with @Client

environment:
  sdk: ^3.5.0

dependencies:
  boot:
    path: ../../../../packages/boot
  boot_http_client:
    path: ../../../../packages/boot_http_client

dev_dependencies:
  boot_generator:
    path: ../../../../packages/boot_generator
  boot_http_client_generator:
    path: ../../../../packages/boot_http_client_generator
  boot_test:
    path: ../../../../packages/boot_test
  build_runner: ^2.4.0
  test: ^1.25.0

dependency_overrides:
  boot:
    path: ../../../../packages/boot
  boot_core:
    path: ../../../../packages/boot_core
  boot_aop:
    path: ../../../../packages/boot_aop
  boot_events:
    path: ../../../../packages/boot_events
  boot_scheduling:
    path: ../../../../packages/boot_scheduling
  boot_serialization:
    path: ../../../../packages/boot_serialization
  boot_http_common:
    path: ../../../../packages/boot_http_common
  boot_http:
    path: ../../../../packages/boot_http
  boot_http_client:
    path: ../../../../packages/boot_http_client
  boot_http_client_generator:
    path: ../../../../packages/boot_http_client_generator
  boot_security:
    path: ../../../../packages/boot_security
  boot_security_jwt:
    path: ../../../../packages/boot_security_jwt
  boot_generator:
    path: ../../../../packages/boot_generator
  boot_test:
    path: ../../../../packages/boot_test
