builders:
  client_builder:
    import: "package:boot_http_client_generator/builder.dart"
    builder_factories: ["clientBuilder"]
    build_extensions: {".dart": [".boot_client.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
