name: boot_test
description: Testing utilities for Boot framework applications.
repository: https://github.com/zonnedev/dart-boot/tree/master/packages/boot_test
version: 0.2.0

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  boot: ^0.2.0
  shelf: ^1.4.0
  test: ^1.25.0

topics:
  - boot
  - testing
  - server
