name: boot_http_client
description: HTTP client for Boot (@Client, HttpClientBuilder).
repository: https://github.com/zonnedev/dart-boot/tree/main/packages/boot_http_client
version: 0.1.1+1
environment:
  sdk: ^3.5.0
resolution: workspace
dependencies:
  boot_core:
    path: ../boot_core
  boot_aop:
    path: ../boot_aop
  boot_http_common:
    path: ../boot_http_common
  http: ^1.0.0

dev_dependencies:
  test: ^1.25.0

topics:
  - boot
  - http-client
  - http
