name: boot_http_client
description: HTTP client for Boot (@Client, HttpClientBuilder).
repository: https://github.com/jfsanchez/dart-boot/tree/main/packages/boot_http_client
version: 0.1.0
environment:
  sdk: ^3.5.0
resolution: workspace
dependencies:
  boot_core:
    path: ../boot_core
  boot_aop:
    path: ../boot_aop
  boot_http_common:
    path: ../boot_http_common
  http: ^1.0.0
