name: boot_scheduling
description: Task scheduling for Boot (@Scheduled).
repository: https://github.com/jfsanchez/dart-boot/tree/main/packages/boot_scheduling
version: 0.1.1
environment:
  sdk: ^3.5.0
resolution: workspace
dependencies:
  boot_core:
    path: ../boot_core
