name: boot_scheduling
description: Task scheduling for Boot (@Scheduled).
repository: https://github.com/zonnedev/dart-boot/tree/master/packages/boot_scheduling
version: 0.1.1+2
environment:
  sdk: ^3.5.0
resolution: workspace
dependencies:
  boot_core: ^0.1.0

dev_dependencies:
  test: ^1.25.0

topics:
  - boot
  - scheduling
  - cron
  - tasks
