builders:
  aop_builder:
    import: "package:boot_aop_generator/builder.dart"
    builder_factories: ["aopBuilder"]
    build_extensions: {".dart": [".boot_aop.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
