name: boot
description: Boot Framework — compile-time DI and HTTP framework for Dart. Umbrella package.
repository: https://github.com/zonnedev/dart-boot/tree/master/packages/boot
version: 0.1.1+4

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  boot_core: ^0.1.2+2
  boot_aop: ^0.1.1+3
  boot_events: ^0.1.1+3
  boot_scheduling: ^0.1.1+3
  boot_serialization: ^0.1.1+4
  boot_http: ^0.1.1+4
  boot_http_client: ^0.1.1+4

dev_dependencies:
  test: ^1.25.0

topics:
  - boot
  - server
  - dependency-injection
  - framework
  - http
