builders:
  controller_builder:
    import: "package:boot_http_generator/builder.dart"
    builder_factories: ["controllerBuilder"]
    build_extensions: {".dart": [".boot_route.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
