name: boot_aop
description: AOP (Aspect-Oriented Programming) support for Boot.
repository: https://github.com/jfsanchez/dart-boot/tree/main/packages/boot_aop
version: 0.1.0
environment:
  sdk: ^3.5.0
resolution: workspace
dependencies:
  boot_core:
    path: ../boot_core
