name: boot_aop
description: AOP (Aspect-Oriented Programming) support for Boot.
repository: https://github.com/zonnedev/dart-boot/tree/master/packages/boot_aop
version: 0.2.0
environment:
  sdk: ^3.5.0
resolution: workspace
dependencies:
  boot_core: ^0.2.0

dev_dependencies:
  test: ^1.25.0

topics:
  - boot
  - aop
  - interceptor
  - proxy
