/// Identifies an annotation type by its fully qualified package URI.
///
/// Used to query [AnnotationValue] instances on [BeanDefinition] without
/// needing to import the annotation class at runtime.
///
/// Example:
/// ```dart
/// const serverFilter = AnnotationType('package:boot_http_common/src/http/filter.dart#ServerFilter');
/// ```
class AnnotationType {
  final String uri;
  const AnnotationType(this.uri);

  @override
  bool operator ==(Object other) => other is AnnotationType && other.uri == uri;

  @override
  int get hashCode => uri.hashCode;

  @override
  String toString() => uri;
}

/// A compile-time resolved annotation instance with its member values.
///
/// Generated by the Boot compiler for every annotation on a bean class.
/// Available at runtime via [BeanDefinition.annotationMetadata].
class AnnotationValue {
  final AnnotationType type;
  final Map<String, dynamic> values;

  const AnnotationValue(this.type, [this.values = const {}]);
}

/// Extension for querying annotation metadata on a [BeanDefinition].
extension AnnotationMetadataQuery on List<AnnotationValue> {
  /// Find an annotation by type.
  AnnotationValue? byType(AnnotationType type) {
    for (final a in this) {
      if (a.type == type) return a;
    }
    return null;
  }

  /// Check if an annotation is present.
  bool hasType(AnnotationType type) => any((a) => a.type == type);
}
